/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.DecimalFormat;



/**
 *
 * @author xavis
 */
public class calculadora extends javax.swing.JFrame {

    private boolean punto=true;
    String valor1, valor2, operacion, contenido;
    Double resultado;

    
    
    public calculadora() {               
        initComponents();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        division = new javax.swing.JLabel();
        resta = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();
        barra = new javax.swing.JLabel();
        ALABEL = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        txtOperacion = new javax.swing.JLabel();
        btnPorcentaje = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        btnBorrarUno = new javax.swing.JButton();
        btn1x = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        multiplicacion = new javax.swing.JLabel();
        btnMultiplicar = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xavimàtíca");
        setBackground(new java.awt.Color(103, 252, 225));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/divide.png"))); // NOI18N
        jPanel1.add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/resta.png"))); // NOI18N
        jPanel1.add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/suma.png"))); // NOI18N
        jPanel1.add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, -1, -1));

        barra.setBackground(new java.awt.Color(103, 252, 225));
        barra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra.setOpaque(true);
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 30));

        ALABEL.setText("XAVI SANCHEZ");
        jPanel1.add(ALABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        txtResultado.setBackground(new java.awt.Color(133, 133, 133));
        txtResultado.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 72)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(102, 102, 102));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtResultado.setToolTipText("");
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 510, 110));

        txtOperacion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(153, 153, 153));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 500, 30));

        btnPorcentaje.setBackground(new java.awt.Color(133, 133, 133));
        btnPorcentaje.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btnPorcentaje.setForeground(new java.awt.Color(133, 133, 133));
        btnPorcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btnPorcentaje.setText("%");
        btnPorcentaje.setBorder(null);
        btnPorcentaje.setBorderPainted(false);
        btnPorcentaje.setContentAreaFilled(false);
        btnPorcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPorcentaje.setMaximumSize(new java.awt.Dimension(130, 80));
        btnPorcentaje.setMinimumSize(new java.awt.Dimension(130, 80));
        btnPorcentaje.setPreferredSize(new java.awt.Dimension(130, 80));
        btnPorcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });
        jPanel1.add(btnPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        btnBorrarTodo.setBackground(new java.awt.Color(133, 133, 133));
        btnBorrarTodo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btnBorrarTodo.setForeground(new java.awt.Color(133, 133, 133));
        btnBorrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btnBorrarTodo.setText("C");
        btnBorrarTodo.setBorder(null);
        btnBorrarTodo.setBorderPainted(false);
        btnBorrarTodo.setContentAreaFilled(false);
        btnBorrarTodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarTodo.setMaximumSize(new java.awt.Dimension(130, 80));
        btnBorrarTodo.setMinimumSize(new java.awt.Dimension(130, 80));
        btnBorrarTodo.setPreferredSize(new java.awt.Dimension(130, 80));
        btnBorrarTodo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        btnBorrarUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_borrar.png"))); // NOI18N
        btnBorrarUno.setBorder(null);
        btnBorrarUno.setBorderPainted(false);
        btnBorrarUno.setContentAreaFilled(false);
        btnBorrarUno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_borrar_press.png"))); // NOI18N
        btnBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        btn1x.setBackground(new java.awt.Color(133, 133, 133));
        btn1x.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 30)); // NOI18N
        btn1x.setForeground(new java.awt.Color(133, 133, 133));
        btn1x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn1x.setText("1/x");
        btn1x.setBorder(null);
        btn1x.setBorderPainted(false);
        btn1x.setContentAreaFilled(false);
        btn1x.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1x.setMaximumSize(new java.awt.Dimension(130, 80));
        btn1x.setMinimumSize(new java.awt.Dimension(130, 80));
        btn1x.setPreferredSize(new java.awt.Dimension(130, 80));
        btn1x.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1xActionPerformed(evt);
            }
        });
        jPanel1.add(btn1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btnX2.setBackground(new java.awt.Color(133, 133, 133));
        btnX2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btnX2.setForeground(new java.awt.Color(133, 133, 133));
        btnX2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btnX2.setText("x²");
        btnX2.setBorder(null);
        btnX2.setBorderPainted(false);
        btnX2.setContentAreaFilled(false);
        btnX2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnX2.setMaximumSize(new java.awt.Dimension(130, 80));
        btnX2.setMinimumSize(new java.awt.Dimension(130, 80));
        btnX2.setPreferredSize(new java.awt.Dimension(130, 80));
        btnX2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        btnRaiz.setBackground(new java.awt.Color(133, 133, 133));
        btnRaiz.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btnRaiz.setForeground(new java.awt.Color(133, 133, 133));
        btnRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btnRaiz.setText("²√x");
        btnRaiz.setBorder(null);
        btnRaiz.setBorderPainted(false);
        btnRaiz.setContentAreaFilled(false);
        btnRaiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRaiz.setMaximumSize(new java.awt.Dimension(130, 80));
        btnRaiz.setMinimumSize(new java.awt.Dimension(130, 80));
        btnRaiz.setPreferredSize(new java.awt.Dimension(130, 80));
        btnRaiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2.png"))); // NOI18N
        btnDividir.setBorder(null);
        btnDividir.setBorderPainted(false);
        btnDividir.setContentAreaFilled(false);
        btnDividir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2press.png"))); // NOI18N
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        jPanel1.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/multiplo.png"))); // NOI18N
        jPanel1.add(multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 40, -1));

        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2.png"))); // NOI18N
        btnMultiplicar.setBorder(null);
        btnMultiplicar.setBorderPainted(false);
        btnMultiplicar.setContentAreaFilled(false);
        btnMultiplicar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2press.png"))); // NOI18N
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        btn9.setBackground(new java.awt.Color(103, 252, 225));
        btn9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn9.setForeground(new java.awt.Color(103, 252, 225));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setMaximumSize(new java.awt.Dimension(130, 80));
        btn9.setMinimumSize(new java.awt.Dimension(130, 80));
        btn9.setPreferredSize(new java.awt.Dimension(130, 80));
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        btn8.setBackground(new java.awt.Color(49, 185, 241));
        btn8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn8.setForeground(new java.awt.Color(49, 185, 241));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setMaximumSize(new java.awt.Dimension(130, 80));
        btn8.setMinimumSize(new java.awt.Dimension(130, 80));
        btn8.setPreferredSize(new java.awt.Dimension(130, 80));
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        btn7.setBackground(new java.awt.Color(59, 196, 239));
        btn7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn7.setForeground(new java.awt.Color(59, 196, 239));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setMaximumSize(new java.awt.Dimension(130, 80));
        btn7.setMinimumSize(new java.awt.Dimension(130, 80));
        btn7.setPreferredSize(new java.awt.Dimension(130, 80));
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        btn4.setBackground(new java.awt.Color(59, 196, 239));
        btn4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn4.setForeground(new java.awt.Color(59, 196, 239));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setMaximumSize(new java.awt.Dimension(130, 80));
        btn4.setMinimumSize(new java.awt.Dimension(130, 80));
        btn4.setPreferredSize(new java.awt.Dimension(130, 80));
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        btn5.setBackground(new java.awt.Color(49, 185, 241));
        btn5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn5.setForeground(new java.awt.Color(49, 185, 241));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setMaximumSize(new java.awt.Dimension(130, 80));
        btn5.setMinimumSize(new java.awt.Dimension(130, 80));
        btn5.setPreferredSize(new java.awt.Dimension(130, 80));
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        btn6.setBackground(new java.awt.Color(103, 252, 225));
        btn6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn6.setForeground(new java.awt.Color(103, 252, 225));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setMaximumSize(new java.awt.Dimension(130, 80));
        btn6.setMinimumSize(new java.awt.Dimension(130, 80));
        btn6.setPreferredSize(new java.awt.Dimension(130, 80));
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        btnRestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2.png"))); // NOI18N
        btnRestar.setBorder(null);
        btnRestar.setBorderPainted(false);
        btnRestar.setContentAreaFilled(false);
        btnRestar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2press.png"))); // NOI18N
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2.png"))); // NOI18N
        btnSumar.setBorder(null);
        btnSumar.setBorderPainted(false);
        btnSumar.setContentAreaFilled(false);
        btnSumar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo2press.png"))); // NOI18N
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, -1, -1));

        btn3.setBackground(new java.awt.Color(84, 229, 231));
        btn3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn3.setForeground(new java.awt.Color(84, 229, 231));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setMaximumSize(new java.awt.Dimension(130, 80));
        btn3.setMinimumSize(new java.awt.Dimension(130, 80));
        btn3.setPreferredSize(new java.awt.Dimension(130, 80));
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        btn2.setBackground(new java.awt.Color(49, 185, 241));
        btn2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn2.setForeground(new java.awt.Color(49, 185, 241));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setMaximumSize(new java.awt.Dimension(130, 80));
        btn2.setMinimumSize(new java.awt.Dimension(130, 80));
        btn2.setPreferredSize(new java.awt.Dimension(130, 80));
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, -1));

        btn1.setBackground(new java.awt.Color(49, 185, 241));
        btn1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn1.setForeground(new java.awt.Color(49, 185, 241));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setMaximumSize(new java.awt.Dimension(130, 80));
        btn1.setMinimumSize(new java.awt.Dimension(130, 80));
        btn1.setPreferredSize(new java.awt.Dimension(130, 80));
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        btn0.setBackground(new java.awt.Color(58, 195, 239));
        btn0.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btn0.setForeground(new java.awt.Color(58, 195, 239));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.setMaximumSize(new java.awt.Dimension(130, 80));
        btn0.setMinimumSize(new java.awt.Dimension(130, 80));
        btn0.setPreferredSize(new java.awt.Dimension(130, 80));
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, -1));

        btnPunto.setBackground(new java.awt.Color(61, 201, 237));
        btnPunto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(61, 201, 237));
        btnPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1.png"))); // NOI18N
        btnPunto.setText(".");
        btnPunto.setBorder(null);
        btnPunto.setBorderPainted(false);
        btnPunto.setContentAreaFilled(false);
        btnPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPunto.setMaximumSize(new java.awt.Dimension(130, 80));
        btnPunto.setMinimumSize(new java.awt.Dimension(130, 80));
        btnPunto.setPreferredSize(new java.awt.Dimension(130, 80));
        btnPunto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_tipo1press.png"))); // NOI18N
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, -1, -1));

        btnIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_igual.png"))); // NOI18N
        btnIgual.setBorder(null);
        btnIgual.setBorderPainted(false);
        btnIgual.setContentAreaFilled(false);
        btnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_igual_press.png"))); // NOI18N
        btnIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_igual_press.png"))); // NOI18N
        btnIgual.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/button_igual_press.png"))); // NOI18N
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        jPanel1.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imgs/bg.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 550, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        agregar("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
        valor1=txtOperacion.getText();
        operacion="+";
        txtOperacion.setText(valor1 + " + ");
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btn1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1xActionPerformed
        // TODO add your handling code here:

        if (!txtOperacion.getText().isEmpty()) {
            double numero = Double.parseDouble(txtOperacion.getText());
            double resultado = 1 / numero;
            txtOperacion.setText("1 ÷ " + txtOperacion.getText());
            txtResultado.setText(Double.toString(resultado));
            txtOperacion.setText(txtResultado.getText());
        }
    }//GEN-LAST:event_btn1xActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        if(txtOperacion.getText().length()<=0){
            txtOperacion.setText("0.");
        }
        else if(txtOperacion.getText().contains("0.")){
        txtOperacion.setText(txtOperacion.getText() + "0.");
        }else{
            txtOperacion.setText(txtOperacion.getText()+".");
            punto=false;
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        // TODO add your handling code here:
        valor1=txtOperacion.getText();
        operacion="/";
        txtOperacion.setText(valor1 + " ÷ ");
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        agregar("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        agregar("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed
        // TODO add your handling code here:
        valor1=txtOperacion.getText();
        operacion="%";
        txtOperacion.setText(valor1 + " % ");
    }//GEN-LAST:event_btnPorcentajeActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        agregar("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUnoActionPerformed
        // TODO add your handling code here:
        contenido=txtOperacion.getText();
        if(contenido.length()>0){
            contenido=contenido.substring(0, contenido.length()-1);
            txtOperacion.setText(contenido);
        }
    }//GEN-LAST:event_btnBorrarUnoActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        agregar("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
        valor1=txtOperacion.getText();
        operacion="*";
        txtOperacion.setText(valor1 + " × ");
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        // TODO add your handling code here:
        valor1=txtOperacion.getText();
        operacion="-";
        txtOperacion.setText(valor1 + " - ");
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2ActionPerformed
        // TODO add your handling code here:
        if (!txtOperacion.getText().isEmpty()) {
            double resultado = Double.parseDouble(txtResultado.getText());
            txtOperacion.setText(txtResultado.getText() + "²");
            txtResultado.setText(Double.toString(Math.pow(resultado, 2)));
            txtOperacion.setText(txtResultado.getText());
        }
    }//GEN-LAST:event_btnX2ActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        // TODO add your handling code here:
        txtOperacion.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        agregar("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        String[] partesOperacion = txtOperacion.getText().split("\\s+");
        if (partesOperacion.length == 3) {
            valor2 = partesOperacion[2];
            if(valor2.equals("0") && operacion.equals("/")){
                txtResultado.setText("ERROR");
            }else{
                String resultado = operaciones.calcular(valor1, valor2, operacion);
                txtResultado.setText(resultado);
                txtOperacion.setText(txtResultado.getText());
            }
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        agregar("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        agregar("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        agregar("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        // TODO add your handling code here:
    contenido = txtOperacion.getText();
    if (contenido.length() > 0) {
        double resultadoNumerico = Math.sqrt(Double.parseDouble(contenido));
    DecimalFormat df = new DecimalFormat("#.##"); 
    String resultadoFormateado = df.format(resultadoNumerico);
        txtOperacion.setText("√" + contenido);
        txtResultado.setText(resultadoFormateado);
        txtOperacion.setText(txtResultado.getText());
}

    }//GEN-LAST:event_btnRaizActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        agregar("2");
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
                
    }
    public void agregar(String num) {
        txtOperacion.setText(txtOperacion.getText() + num);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALABEL;
    private javax.swing.JLabel barra;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1x;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnBorrarUno;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btnX2;
    private javax.swing.JLabel division;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel multiplicacion;
    private javax.swing.JLabel resta;
    private javax.swing.JLabel suma;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables

    
    }

